[tool.poetry]
name = "lilac-docs"
version = "0.0.0"
authors = ["Lilac AI Inc. <info@lilacml.com>"]
description = "Documentation for Lilac"

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
autodoc-pydantic = "^1.9.0"
sphinx = "^7.1.0"
furo = "^2023.5.20"
lilacai = { path = "..", develop = true }
