name: CLI

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Test CLI
        run: |
          chmod +x ./integration_tests/run_integration_tests.sh
          ./integration_tests/run_integration_tests.sh
        shell: bash
