on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.13'
          cache: 'poetry'
      - name: Install dependencies
        run: |
          ./scripts/setup_py.sh

      - name: Lint python
        run: |
          poetry run ./scripts/lint_py.sh
      - name: Test python
        run: |
          poetry run ./scripts/test_py.sh
